[package]
name = "server_stats"
version = "0.1.0"
authors = ["MTRNord <mtrnord1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
influxdb-client = "0.1.4"
tokio = { version = "1", features = ["full"] }
color-eyre = "0.5"
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }
tokio-cron-scheduler = "0.2.1"
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "postgres" ] }
futures = "0.3.14"
trust-dns-resolver = { version = "0.20", features = ["dns-over-rustls"] }
regex = "1"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
once_cell = "1.7.2"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2.4"
clap = "3.0.0-beta.2"


# Use for cargo flamegraph
#[profile.release]
#debug = true